### ISSUE TITLE
Invalid URL in repositories block of pom.xml

### ISSUE THREAD

**Issue by jukutr** [web-eid/web-eid-spring-boot-example#21]
In the `<repositories>` block in pom.xml file, there is an URL in a comment, referring to "https://github.community/t/download-from-github-package-registry-without-authentication/14407". This link seems to be broken: it redirects to "https://github.com/orgs/community/discussions/". which doesn't contain any useful information.

Also, the `<releases>` and `<snapshots>` seem to be already enabled by default. Is there any reason why they are explicitly enabled in the `<repositories>` block?

**Comment by mrts** [comment]
Thanks, both issues fixed in b31e3693ddb5e5dc4eff74834e5a58cd82f3e5c1.
